### ISSUE TITLE
No such file or directory: 'sam_hq_vit_h.pth'

### ISSUE THREAD

**Issue by Baobaon** [kevin-ssy/CLIP_as_RNN#8]
The model is running on cuda
Traceback (most recent call last):
  File "demo.py", line 206, in <module>
    sam_pipeline = load_sam(cfg, device)
  File "demo.py", line 166, in load_sam
    pipelines = SAMPipeline(
  File "/data/server03/clip_as_rnn/sam/sam.py", line 67, in __init__
    self.sam = sam_model_registry[self.model_type](checkpoint=self.checkpoint)
  File "/home/server03/anaconda3/envs/cn/lib/python3.8/site-packages/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/home/server03/anaconda3/envs/cn/lib/python3.8/site-packages/segment_anything/build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sam_hq_vit_h.pth'

**Comment by runjiali-rl** [comment]
Hi,

Please download the sam hq weight from here
https://github.com/SysCV/sam-hq

Thanks!
